import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Badge } from "@/components/deck/Badge";
import { Panel } from "@/components/deck/Panel";
import { Skeleton } from "@/components/deck/Skeleton";
function GaugeRing() {
    return (_jsxs("svg", { viewBox: "0 0 160 160", className: "h-40 w-40", "aria-hidden": true, children: [_jsx("circle", { cx: "80", cy: "80", r: "62", fill: "none", stroke: "rgba(255,255,255,0.06)", strokeWidth: "10" }), _jsx("circle", { cx: "80", cy: "80", r: "62", fill: "none", stroke: "rgba(34,211,238,0.28)", strokeWidth: "10", strokeLinecap: "round", strokeDasharray: "2 12", strokeDashoffset: "0", transform: "rotate(-90 80 80)" }), Array.from({ length: 24 }).map((_, i) => {
                const a = (i / 24) * Math.PI * 2;
                return (_jsx("line", { x1: 80 + Math.cos(a) * 54, y1: 80 + Math.sin(a) * 54, x2: 80 + Math.cos(a) * 49, y2: 80 + Math.sin(a) * 49, stroke: "rgba(255,255,255,0.14)", strokeWidth: "1" }, i));
            })] }));
}
export function ResultStage() {
    return (_jsxs(Panel, { eyebrow: "Result \u00B7 live stage", title: "Prediction", right: _jsx(Badge, { tone: "signal", children: "calibration" }), bodyClassName: "p-5", children: [_jsxs("div", { className: "flex flex-col items-center pb-2", children: [_jsxs("div", { className: "relative", children: [_jsx(GaugeRing, {}), _jsxs("div", { className: "absolute inset-0 flex flex-col items-center justify-center", children: [_jsx("span", { className: "font-mono text-3xl font-medium text-ink-3", children: "\u2014" }), _jsx("span", { className: "mt-1 font-mono text-[9px] uppercase tracking-[0.2em] text-ink-3", children: "failure probability" })] })] }), _jsxs("p", { className: "mt-2 font-mono text-[10px] text-ink-3", children: ["decision threshold ", _jsx("span", { className: "text-ink-2", children: "0.50" })] }), _jsxs("div", { className: "mt-3 flex flex-wrap items-center justify-center gap-1.5", children: [_jsx(Badge, { tone: "elevated", children: "simulated fallback" }), _jsx(Badge, { tone: "neutral", children: "decision support only" })] })] }), _jsxs("div", { className: "mt-2 space-y-4 border-t border-hairline pt-4", children: [_jsxs("div", { children: [_jsx("p", { className: "font-mono text-[10px] uppercase tracking-[0.18em] text-ink-3", children: "Failure modes" }), _jsx("div", { className: "mt-2 flex flex-wrap gap-2", children: [0, 1, 2].map((i) => (_jsx(Skeleton, { className: "h-6 w-20 rounded-full" }, i))) })] }), _jsxs("div", { children: [_jsx("p", { className: "font-mono text-[10px] uppercase tracking-[0.18em] text-ink-3", children: "Recommended action" }), _jsxs("div", { className: "mt-2 space-y-2", children: [_jsx(Skeleton, { className: "h-3.5 w-full" }), _jsx(Skeleton, { className: "h-3.5 w-4/5" })] })] })] })] }));
}
